### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by hzoo** [hzoo/shengji#2]
### Discussion of UI
- [ ] Styling: less/sass, normalize, not bootstrap
- [ ] Cards themselves: (are we going to use pictures, svg, icons)?
  - https://github.com/donpark/scalable-css-playing-cards
- [ ] Animations?
- [ ] Layout of cards (player's hands, playing area, etc) and statistics (current level, suit, points)
  - How does it scale with 4, 5, 6, 7 people?
- [ ] Menus/Settings/Multiplayer Rooms
- [ ] UX
  - Show winning hand somehow (highlight the current highest hand) and if on your team
  - Show the starting player and direction of play
### Examples of card games:

> I think the older ones look well old. Green background, regular playing cards, and those generic names/faces. I guess that's because they use normal playing cards and want to make it seem like the real thing but it doesn't that great to me.

Full Tilt Poker: 2004?
![Full Tilt Poker](http://www.fulltilt.com/images/com/en/content/how-to-play/getting-started/table-section.jpg)

[Tractor](http://www.kongregate.com/games/auway/tractor): against AI, traditional style UI (2008)
![Tractor](http://i.imgur.com/pGQ6qDB.png)

[Tractor for Android](https://play.google.com/store/apps/details?id=com.android.tractor&hl=en): Tractor on Android (2009)
![Tractor for Android](https://lh3.ggpht.com/u-Okd6WcwBJZYoTkQtw0Pw78jt8jhliEkFkrsp7HnRSCcPBEEMqPGWaMY_rhGEPW8DLi=h310-rw)

[Dominion](https://www.playdominion.com/Dominion/gameClient.html): deck building game - online version (2013)
![Dominion](http://i.imgur.com/mR7T99s.jpg)

[Hearthstone](http://us.battle.net/hearthstone/en/?-): a magic / deck building game (2014)
![Hearthstone](http://i.imgur.com/xHbzyBR.jpg)

**Comment by kumquatexpress** [comment]
As far as assets go, cards can be basic until later. The gameplay isn't dependent on whether a player can see the other hands since everyone has equal card counts at all times, so scaling would be much easier if only players were shown, with no reserved "hand space". That way other players could just be spaced out in 270/n degrees no problem (if your own hand takes up one whole side of the rectangle).

I think hearthstone card play effects and sounds would be pretty cool, though not a priority either. Basic functionality can be just using one of the js easing libraries.

**Comment by hzoo** [comment]
Thanks for chiming in Boyang!

Yeah I'l probably find a either image/css cards library. The animations would be a great addition. Yeah for starters the cards will just appear. It will be an in place sort because of the 'jiao pai' or initial dealing thing. Yeah we will probably need to come up with the correct names/wording.

In the [previous one](https://github.com/hzoo/Tuolaji-Nonoba/blob/master/Flash/MyGame.as#L717) it looks like I calculated the angle and also the cards haha. Yeah you're right since everyone always has the same # of cards at the end of each turn we shouldn't have to show the cards.

We could experiment with other ways of laying out the cards as well - although maybe the circular pattern is best? We could even do it top -> bottom as long as we highlight the player id/number. Or separate it by which team you are on. This is digital anyway and I don't think we need to adhere to how its actually laid out unless it helps with learning it.

**Comment by kumquatexpress** [comment]
There are lots of fun things we can do with the ui and cards, off the top of my head card backs and different face cards. Just keeping the cards as image assets should be fine for an mvp, later on we can spreadsheet them for compression. 

This is definitely less of a concern than the design issue above so no hurries
