### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by hzoo** [hzoo/shengji#5]
- [x] README (what should go here)
  - [x] simple info
  - [x] how to run/run tests
- [x] CONTRIBUTING
  - [x] how to make a pull request/etc
  - [x] coding style
  - [x] commit message
- [x] API Docs
  - [x] use jsDoc
  - [x] add jscs linting of jsDoc

**Comment by hzoo** [comment]
I guess the readme is good for now

**Comment by kumquatexpress** [comment]
API docs started, there are more shiny things possible on that front but not necessary for the time being
